services:
  mariadb:
    image: mariadb:10.5
    container_name: mariadb_container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: HeartRate
      MYSQL_USER: uzivatel
      MYSQL_PASSWORD: heslo
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ../sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ../sql/test_data.sql:/docker-entrypoint-initdb.d/test_data.sql    # Vložení testovacích dat



  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    restart: unless-stopped
    environment:
      PMA_HOST: mariadb  # Odkazuje na název služby v Docker Compose
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"  # Otevře phpMyAdmin na http://localhost:8080

  flask_app:
    build: ../flask
    container_name: flask_container
    restart: unless-stopped
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=mysql+pymysql://uzivatel:heslo@mariadb:3306/HeartRate
    depends_on:
      - mariadb
    volumes:
      - ../flask:/app  # Mapování složky flask do kontejneru
    command: ["python", "run.py"]  # Spuštění Flask aplikace

volumes:
  mariadb_data:
